---
title: Code Design Guidelines
weight: 5
summary: The code design guidelines are rules that must be met for any
         contribution to KiCad's application code base.
---

:toc:

== 1. Introduction

The purpose of this document is to provide a guide for KiCad developers about
source code dos and don'ts in KiCad. It is not a comprehensive guide because it
does not cover all topics.  However, it is expected that all of the topics
covered by this document are followed by all developers contributing code to
the KiCad project.

== 2. Library Dependencies

KiCad is a cross platform project.  Therefore, all dependency libraries must
be packaged for all
https://www.kicad.org/help/system-requirements/[supported platforms].
If packages are not available on a given platform, it is the responsibility of
the developer introducing any new dependencies to ensure that they are packaged
before submitting the new dependency.  Platform specific features will not be
accepted.

== 3. Low Level Object Design

All KiCad low level objects not directly related to user interface design must
be free of user interface code dependencies.  This includes all `SCH_*`, `LIB_*`,
`PCB_*`, `FP_*`, and I/O plugin objects.

:link-with-underscores: https://docs.wxwidgets.org/3.0/group__group__funcmacro__debug.html

NOTE: The only exception is the {link-with-underscores}[wxWidgets Debugging Macros].
      The reason for this is that the wxWidgets user interface code is only
      used in debug builds.  This has the advantage of developers being made
      aware of coding issues without having to run from the command line or
      in a debugger to see assertion messages.


=== 3.1. std::string vs wxString

When possible, use std::string for internal kicad data structures and treat the contents of the std::string
as utf8. Convert to `wxString` for interacting with user interfaces only.

== 4. Integer Types

Where possible, integer types from `cstdint` such as `int32_t`, `int64_t` should be used over basic
types like `int` `long int` `long long int`. 

The explicitly named types from `cstdint` make the intention clear and avoid accidental
bugs such as forgetting `long int` is 64-bit on Linux and 32-bit on Windows.
