---
title: PCB File Format
weight: 5
---

WARNING: This page is a work in progress and is out of date with changes made for KiCad 6.0
         but will eventually be updated to reflect the latest changes.

NOTE: This file format was introduced with the launch of KiCad 4.0


== Syntax
* Based on the Specctra DSN syntax.
* Token definitions delimited by opening `(` and closing ')' parenthesis.
* All tokens are lowercase.
* Tokens cannot contain any white space characters or special characters other than the
  underscore '_' character.
* All strings are quoted using the double quote character (") and are UTF-8 encoded.
* Tokens can have zero or more attributes.
* Human readability is a design goal.

NOTE: Prior to version 6 of KiCad, strings were only quoted when necessary.  Saving an older board
      file to the latest file format will result in these strings being quoted even though there
      is no functional change in the board itself.

=== Conventions

In order to use this document properly, there are a few notation conventions that must be
understood.

* Token attributes are upper case descriptive names.  For example `(at X Y)`, X is the
  horizontal coordinate and Y is the vertical coordinate.
* Some tokens have a limited number of possible attribute values which are separated by a
  logical or character '|'.  For example `(visible yes|no)` the only valid attributes for
  the `visible` token are `yes` or `no`.
* Some tokens have optional attributes which are enclosed in square braces.  For example
  `(paper A0 [portrait])` the page portrait setting is optional.


== Coordinates and Sizes
* All values are given in millimeters.
* Exponential floating point values are not used for readability purposes.
* The minimum internal unit is nanometers so there is maximum resolution of six decimal places
  or 0.000001 mm.  Any precision beyond six places will be truncated.
* All coordinates are relative to the origin of their containing object.


== Layers

All drawable board items exist on a `layer` which is defined in the drawable item definition.
All layers can be renamed by the user.

NOTE: Internally, all layer names are canonical.  User defined layer names are only used for
      display and output purposes.

Layers can be specified with the '*' wildcard to represent all layers that match the rest of
the wildcard.  For instance, `*.Cu` represents all of the copper layers.  This only applies
to canonical layers.

=== Layer Syntax

```
(layer <<canonical-layer-names,CANONICAL_NAME>>)
```

=== Capacity

* 60 total layers.
* 32 copper layers.
* 8 paired technical layers for silk screen, solder mask, solder paste, and adhesive.
* 4 user pre-defined layers for drawings, engineering change order (ECO), and comments.
* 1 layer to define the board outline.
* 1 layer to define the board margins.
* 9 optional user definable layers.

[[canonical-layer-names]]
=== Canonical Layer Names

The table below list all of the canonical layer names.

[options="header"]
|====================================================
|Canonical Name | Description
|F.Cu | Front copper layer
|In1.Cu | Inner copper layer 1
|In2.Cu | Inner copper layer 2
|In3.Cu | Inner copper layer 3
|In4.Cu | Inner copper layer 4
|In5.Cu | Inner copper layer 5
|In6.Cu | Inner copper layer 6
|In7.Cu | Inner copper layer 7
|In8.Cu | Inner copper layer 8
|In9.Cu | Inner copper layer 9
|In10.Cu | Inner copper layer 10
|In11.Cu | Inner copper layer 11
|In12.Cu | Inner copper layer 12
|In13.Cu | Inner copper layer 13
|In14.Cu | Inner copper layer 14
|In15.Cu | Inner copper layer 15
|In16.Cu | Inner copper layer 16
|In17.Cu | Inner copper layer 17
|In18.Cu | Inner copper layer 18
|In19.Cu | Inner copper layer 19
|In20.Cu | Inner copper layer 20
|In21.Cu | Inner copper layer 21
|In22.Cu | Inner copper layer 22
|In23.Cu | Inner copper layer 23
|In24.Cu | Inner copper layer 24
|In25.Cu | Inner copper layer 25
|In26.Cu | Inner copper layer 26
|In27.Cu | Inner copper layer 27
|In28.Cu | Inner copper layer 28
|In29.Cu | Inner copper layer 29
|In30.Cu | Inner copper layer 30
|B.Cu | Back copper layer
|B.Adhesive | Back adhesive layer
|F.Adhesive | Front adhesive layer
|B.Paste | Back solder paste layer
|F.Paste| Front solder paste layer
|B.Silkscreen | Back silk screen layer
|F.Silkscreen | Front silk screen layer
|B.Mask | Back solder mask layer
|F.Mask | Front solder mask layer
|User.Drawings | User drawing layer
|User.Comments | User comment layer
|User.Eco1 | User engineering change order layer 1
|User.Eco2 | User engineering change order layer 2
|Edge.Cu | Board outline layer
|F.Courtyard | Footprint front courtyard layer
|B.Courtyard | Footprint back courtyard layer
|F.Fab | Footprint front fabrication layer
|B.Fab | Footprint back fabrication layer
|User.1 | User definable layer 1
|User.2 | User definable layer 2
|User.3 | User definable layer 3
|User.4 | User definable layer 4
|User.5 | User definable layer 5
|User.6 | User definable layer 6
|User.7 | User definable layer 7
|User.8 | User definable layer 8
|User.9 | User definable layer 9
|====================================================


[[text-effects]]
== Text Effects

All text objects can have an optional `effects` section that defines how the text is displayed.

=== Text Effect Syntax

```
  (effects (font (size HEIGHT WIDTH ) [(thickness THICKNESS)] [bold] [italic])
    [(justify [left | right] [top | bottom] [mirror])]
    [hide]
  )
```

* The `font` token defines the font height, width, line thickness, and if the text should be
  drawn bold and/or italicized.
* The optional `justify` token defines if the text is justified horizontal right or left and/or
  vertically top or bottom and mirrored.  If the justification is not defined, then the text
  is center justified both horizontally and vertically and not mirrored.
* The optional `hide` token defines if the text is visible or hidden.


== Layout

A board file includes the following sections:

* Header
* General
* Layers
* Setup
* Properties
* Nets
* Footprints
* Graphic Items
* Tracks
* Zones

NOTE: The section order is not critical other than the header must be the first token.  Some
      sections can may omitted.

=== Header Section

This section defined the file version and generator information that defines the appropriate
KiCad board file format.

==== Header Syntax

```
(kicad_pcb (version VERSION) (generator GENERATOR)
  ... contents of board file.
)
```

* The `kicad_pcb` token defines this file as a KiCad board file and is required.
* The `version` token defines the board version as YYYYMMDD date.
* The `generator` token defines the program used to write the file.

NOTE: Third party scripts should not use `pcbnew` as the generator identifier.  Please use some
      other identifier so that bugs introduced by third party generators are not confused with
      the board file created by KiCad.

=== General Section

This section contains general information about the board.

==== General Section Syntax

```
  (general
    (thickness THICKNESS)
  )
```

* The `thickness` token defines the overall board thickness.

NOTE: The general section only has a single setting.  Most of the previous general section
      setting have been moved into the project file.

=== Page Section

This section defines the board page size and orientation.

==== Page Section Syntax

```
  (paper PAPER_SIZE | WIDTH HEIGHT [portrait] )
```

* The `paper` token defines the board page size.  Valid pages sizes are A0, A1, A2, A3, A4, A5,
  A, B, C, D, or E.
* The width and height are used for custom user defined page sizes.

=== Layers Section

This section defines all of the layers used by the board.

==== Layer Syntax

```
  (layers
    (LAYER_ORDINAL "CANONICAL_NAME" LAYER_TYPE ["USER_NAME"])
    ... remain layers
  )
```

* The layer ordinal is a number used to associate the layer stack ordering.  This is mostly
  to ensure correct mapping when the number of layers is increased in the future.
* The canonical name is the name defined for internal board use.
* The layer type can be defined as jumper, mixed, power, signal, user.

=== Setup Section

This section stores the current settings such as default item sizes and other options in use
for this board.

==== Setup Syntax

```
  (setup
    [(stackup
      ... see board stack up settings section
    )]
  (pad_to_mask_clearance CLEARANCE)
  [(solder_mask_min_width MINIMUM_WIDTH)]
  [(pad_to_paste_clearance CLEARANCE)]
  [(pad_to_paste_clearance_ratio RATIO)]
  [(aux_axis_origin X Y)]
  [(grid_origin X Y)]
    (pcbplotparams
      ... see plot settings section
  )
```

* The `pad_to_mask_clearance` token defines the clearance between footprint pads and the solder
  mask.
* The optional `solder_mask_min_width` defines the minimum solder mask width.  If not defined,
  the minimum width is zero.
* The optional `pad_to_paste_clearance` defines the clearance between footprint pads and the
  solder paste layer.  If not defined, the clearance is zero.
* The optional `pad_to_paste_clearance_ratio` is the percentage (from 0 to 100) of the footprint
  pad to make the solder paste.  If not defined, the ratio is 100% (the same size as the pad).
* The optional `aux_axis_origin` defines the auxiliary origin if it is set to anything other than
  (0,0).
* The optional `grid_origin` defines the grid original if it is set to anything other than (0,0).

===== Board Stack Up Settings Section

This section defines the board stack up settings and is defined in the settings section.

===== Board Stack Up Syntax

```
    [(stackup
       (layer "NAME" | dielectric NUMBER (type "DESCRIPTION") [(color "COLOR")]
        [(thickness THICKNESS)] [(material "MATERIAL")] [(epsilon_r DIELECTRIC_RESISTANCE)]
        [(loss_tangent LOSS_TANGENT)]
       )
       ... all remaining layers in the actual board stack up order
       [(copper_finish "FINISH")]
       [(dielectric_constraints yes | no)]
       [(edge_connector yes | bevelled)]
       [(castellated_pads yes)]
       [(edge_plating yes)]
    )]
```

* The `layer` token defines the settings for each layer required to manufacture a board including
  the dielectric material between the actual layers defined in the board editor.
** The layer name attribute is either one of the canonical copper or technical layer names listed
   in the table above or `dielectric ID` if it is dielectric layer.
** The layer `type` token defines a string that describes the layer.
** The optional layer `color` token  defines a string that describes the layer color.  This is
   only used on solder mask and silkscreen layers.
** The optional layer `thickness` token defines the thickness of the layer where appropriate.
** The optional layer `material` token defines a string that describes the layer material where
   appropriate.
** The optional layer `epsilon_r` token defines the dielectric constant of the layer material.
** The optional layer `loss_tangent` token defines the dielectric loss tangent of the layer
   material.
* The optional `copper_finish` token is a string that defines the copper finish used to manufacture
  the board.
* The optional `dielectric_contraints` token define if the board should meet all dielectric
  requirements.
* The optional `edge_connector` token defines if the board has an edge connector and if the
  edge connector is bevelled.
* The optional `castellated_pads` token defines if the board edges contain castellated pads.
* The optional `edge_plating` token defines if the board edges should be plated.

==== Plot Settings Section

This section defines the plotting and printing settings and is defined in the settings section.

==== Plot Settings Syntax

```
    (pcbplotparams
      (layerselection HEXADECIMAL_BIT_SET)
      (disableapertmacros true | false)
      (usegerberextensions true | false)
      (usegerberattributes true | false)
      (usegerberadvancedattributes true | false)
      (creategerberjobfile true | false)
      (svguseinch true | false)
      (svgprecision PRECISION)
      (excludeedgelayer true | false)
      (plotframeref true | false)
      (viasonmask true | false)
      (mode MODE)
      (useauxorigin true | false)
      (hpglpennumber NUMBER)
      (hpglpenspeed SPEED)
      (hpglpendiameter DIAMETER)
      (dxfpolygonmode true | false)
      (dxfimperialunits true | false)
      (dxfusepcbnewfont true | false)
      (psnegative true | false)
      (psa4output true | false)
      (plotreference true | false)
      (plotvalue true | false)
      (plotinvisibletext true | false)
      (sketchpadsonfab true | false)
      (subtractmaskfromsilk true | false)
      (outputformat FORMAT)
      (mirror true | false)
      (drillshape SHAPE)
      (scaleselection 1)
      (outputdirectory "PATH")
    )
```

* The `layerselection` token defines a hexadecimal bit set of the layers to plot.
* The `disableapertmacros` token defines if aperture macros are to be used in gerber plots.
* The `usegerberextensions` token defines if the Protel layer file name extensions are to be used
  in gerber plots.
* The `usegerberattributes` token defines if the X2 extensions are used in gerber plots.
* The `usegerberadvancedattributes` token defines if the netlist information should be included
  in gerber plots.
* The `creategerberjobfile` token defines if a job file should be created when plotting gerber
  files.
* The `svguseinch` token defines if inch units should be use when plotting SVG files.
* The `svgprecision` token defines the units precision used when plotting SVG files.
* The `excludeedgelayer` token defines if the board edge layer is plotted on all layers.
* The `plotframeref` token defines if the border and title block should be plotted.
* The `viasonmask` token defines if the vias are to be tented.
* The `mode` token defines the plot mode. An attribute of 1 plots in the normal mode and an
  attribute of 2 plots in the outline (sketch) mode.
* The `useauxorigin` token determines if all coordinates are offset by the defined user origin.
* The `hpglpennumber` token defines the integer pen number used for HPGL plots.
* The `hpglpenspeed` token defines the integer pen speed used for HPGL plots.
* The `hpglpendiameter` token defines the floating point pen size for HPGL plots.
* The `dxfpolygonmode` token defines if the polygon mode should be used for DXF plots.
* The `dxfimperialunits` token defines if imperial units should be used for DXF plots.
* The `dxfusepcbnewfont` token defines if the Pcbnew font (vector font) or the default font
  should be used for DXF plots.
* The `psnegative` token defines if the output should be the negative for PostScript plots.
* The `psa4output` token defines if the A4 page size should be used for PostScript plots.
* The `plotreference` token defines if hidden reference field text should be plotted.
* The `plotvalue` token defines if hidden value field text should be plotted.
* The `plotinvisibletext` token defines if hidden text other than the reference and value fields
  should be plotted.
* The `sketchpadsonfab` token defines if pads should be plotted in the outline (sketch) mode.
* The `subtractmaskfromsilk` toke defines if the solder mask layers should be subtracted from
  the silk screen layers for gerber plots.
* The `outputformat` token defines the last plot type.
** 0 - gerber
** 1 - PostScript
** 2 - SVG
** 3 - DXF
** 4 - HPGL
** 5 - PDF
* The `mirror` token defines if the plot should be mirrored.
* The `drillshape` token defines the type of drill marks used for drill files.
* The `scaleselection` token defines *** Please define ***.
* The `outputdirectory` token defines the path relative to the current project path where the
  plot files will be saved.

=== Properties Section

This section contains user defined properties for the board.  Properties are key/value pairs
that allow the user to define properties for ** DEFINE ME **.  If no properties are defined,
this section will not exist.

=== Property Syntax

```
  (property "KEY" "VALUE")
```

=== Nets Section

This section contains the list of one or more nets that define the connectivity for the board.

=== Net Syntax

```
  (net ORDINAL "NET_NAME")
```

* The `net` token defines a net used for connectivity purposes.
* The oridinal attribute is an increment integer that orders the net.
* The net name is a string that defines the name of the net.

NOTE: The net class section has been moved out of the board file into the design rules file.


=== Footprints Section

This section contains a list of all of the footprint on the board.

NOTE: Prior to version 6, the `footprint` token was referred to as `module`.

=== Footprints Syntax

```
  (footprint "REFERENCE [locked] [placed] (layer "CANONICAL_NAME)
    (tedit TIME_STAMP) (tstamp UUID)
    (at X Y [ORIENTATION])
    [(descr "DESCRIPTION")]
    [(tags "NAME")]
    [(property "KEY" "VALUE")]
    (path "PATH")
    [(autoplace_cost90 COST)]
    [(autoplace_cost180 COST)]
    [(solder_mask_margin MARGIN)]
    [(solder_paste_margin MARGIN)]
    [(solder_paste_ratio RATIO)]
    [(clearance CLEARANCE)]
    [(zone_connect CONNECTION_TYPE)]
    [(thermal_width WIDTH)]
    [(thermal_gap DISTANCE)]
    (attr smd | through_hole [board_only] [exclude_from_pos_files] [exclude_from_bom])
    (fp_text reference "REFERENCE" (at X Y) (layer "CANONICAL_NAME") [hide]
      (<<text-effects,TEXT_EFFECTS>>)
    )
    (fp_text value "VALUE" (at X Y) (layer "CANONICAL_NAME")
      (<<text-effects,TEXT_EFFECTS>>)
    )
    (fp_line (start X Y) (end X Y) (layer "CANONICAL_NAME") (width WIDTH) [(locked)] (tstamp UUID))
    (fp_rect (start X Y) (end X Y) (layer "CANONICAL_NAME") (width WIDTH) [(fill TYPE)] [(locked)] (tstamp UUID))
    (fp_circle (center X Y) (end X Y) (layer "CANONICAL_NAME") (width WIDTH) [(locked)] (tstamp UUID))
    (fp_arc (start X Y) (end X Y) (angle ANGLE) (layer "CANONICAL_NAME") (width WIDTH) [(locked)] (tstamp UUID))
    (fp_poly (pts (xy X Y) ... (xy X Y)) (layer "CANONICAL_NAME") (width WIDTH) [(locked)] (tstamp UUID))
    (fp_curve (pts (xy X Y) (xy X Y) (xy X Y) (xy X Y)) (layer "CANONICAL_NAME") (width WIDTH) [(locked)] (tstamp UUID))
    (pad "NUMBER" TYPE SHAPE (at X Y [ORIENTATION]) [(locked)] (size X Y)
      (drill [oval] DIAMETER [WIDTH] [(offset X Y)])
      (layers "CANONICAL_LAYER_LIST")
      [(property "KEY" "VALUE")]
      [(remove_unused_layer)]
      [(keep_end_layers)]
      [(roundrect_rratio RATIO)]
      [(chamfer_ration RATIO)]
      [(chamfer [top_left] [top_right] [bottom_left] [bottom right])]
    )
    (net NUMBER "NAME") (tstamp UUID)
    [(pinfunction PIN_FUNCTION)]
    [(pintype PIN_TYPE)]
    [(die_length LENGTH)]
    [(solder_mask_margin MARGIN)]
    [(solder_paste_margin MARGIN)]
    [(solder_paste_margin_ratio RATIO)]
    [(clearance CLEARANCE)]
    [(zone_connect ZONE)]
    [(thermal_width WIDTH)]
    [(thermal_gap DISTANCE)]
    [(options (clearance convexhull | outline) rect | circle (anchor PAD_SHAPE))]
    [(primitives
       (gr_line (start X Y) (end X Y))
       (gr_rect (start X Y) (end X Y))
       (gr_arc (start X Y) (end X Y) (angle ANGLE))
       (gr_circle (center X Y) (end X Y))
       (gr_curve (pts (xy X Y) (xy X Y) (xy X Y) (xy X Y)))
       (gr_poly (pts
         (xy X Y) ... (xy X Y))
       )
       (width WIDTH) [(fill yes])]
     )]
    [(zone...)]
    [(group...)]
    (model "3D_MODEL_FILE"
      (at (xyz X Y Z))
      (scale (xyz X Y Z))
      (rotate (xyz X Y Z))
    )
  )
```

=== Graphic Items Section

The graphical items section contains all board items that are outside of the connectivity defined
in the net section.  This includes graphical items on technical, user, and copper layers.

==== Graphical Text

```
  (gr_text TEST (at 62 31) (layer top_side.Cu)
    (effects (font (size 1.5 1.5) (thickness 0.3)))
  )
```

==== Graphical Line

```
  (gr_line (start 58 42) (end 58 29) [(angle 90)] (layer Edge.Cuts) (width 0.15) [(locked)]
    (tstamp UUID)
  )
```

==== Graphical Rectangle

```
  (gr_rect (start %s) (end %s) (layer Edge.Cuts) (width 0.15) [(fill MODE)] [(locked)]
    (tstamp UUID)
  )
```

==== Graphical Circle

```
  (gr_circle (center %s) (end %s) (layer Edge.Cuts) (width 0.15) [(fill MODE)] [(locked)]
    (tstamp UUID)
  )
```

==== Graphical Arc

```
  (gr_arc (start %s) (end %s) (angle %s) (layer Edge.Cuts) (width 0.15) [(locked)]
    (tstamp UUID)
  )
```

==== Graphical Polygon

```
  (gr_poly (pts
    (xy X Y) ... (xy X Y))
    (width 0.15) [(fill MODE)] [(locked)] (tstamp UUID)
  )
```

==== Graphical Curve

```
  (gr_curve (pts (xy X Y) (xy X Y) (xy X Y) (xy X Y)) (layer Edge.Cuts) (width 0.15) [(locked)]
    (tstamp UUID)
  )
```

=== Track Section

This section lists all of segment, via, and arc objects that make up tracks on the board.

==== Track Segment Syntax

```
  (segment (start X Y) (end X Y) (width WIDTH) (layer bottom_side.Cu)
    [(locked)] (net 1) (tstamp UUID)
  )
```

==== Track Via Syntax

```
  (via (at X Y) (size DIAMETER) (drill DIAMETER) (layers "F.Cu" "B.Cu")
    [(locked)] (net 1) (tstamp UUID)
  )
```

==== Track Arc Syntax

```
  (arc (start %s) (mid %s) (end %s) (width %s) (layers "F.Cu" "B.Cu")
    [(locked)] (net 1) (tstamp UUID)
  )
```


=== Zone Section

This section contains the list of zones in the board.  This section is ommitted if there are no
zones on the board.

==== Zone Syntax

```
  (zone (net 3) (net_name "+5V") (layer "In1.Cu") (tstamp 00000000-0000-0000-0000-000056040b2c) (hatch edge 0.508)
    (connect_pads (clearance 0.2794))
    (min_thickness 0.2032)
    (fill yes (thermal_gap 0.381) (thermal_bridge_width 0.381))
    (polygon
      (pts
        (xy 153.289 107.95)
        ...
        (xy 153.082553 110.309705)
      )
    )
    (filled_polygon
      (layer "In1.Cu")
      (pts
        (xy 142.394143 94.825161)
        ...
        (xy 144.892128 95.598417)
      )
    )
  )
```

== Board Example:

```
(kicad_pcb (version 3) (host pcbnew "(2013-02-20 BZR 3963)-testing")

  (general
    (links 2)
    (no_connects 0)
    (area 57.924999 28.924999 74.075001 42.075001)
    (thickness 1.6)
    (drawings 5)
    (tracks 5)
    (zones 0)
    (modules 2)
    (nets 3)
  )

  (page A4)
  (layers
    (15 top_side.Cu signal)
    (2 Inner2.Cu signal)
    (1 Inner1.Cu signal)
    (0 bottom_side.Cu signal)
    (16 B.Adhes user)
    (17 F.Adhes user)
    (18 B.Paste user)
    (19 F.Paste user)
    (20 B.SilkS user)
    (21 F.SilkS user)
    (22 B.Mask user)
    (23 F.Mask user)
    (24 Dwgs.User user)
    (25 Cmts.User user)
    (26 Eco1.User user)
    (27 Eco2.User user)
    (28 Edge.Cuts user)
  )

  (setup
    (last_trace_width 0.254)
    (trace_clearance 0.254)
    (zone_clearance 0.2)
    (zone_45_only no)
    (trace_min 0.254)
    (segment_width 0.2)
    (edge_width 0.15)
    (via_size 0.889)
    (via_drill 0.635)
    (via_min_size 0.889)
    (via_min_drill 0.508)
    (uvia_size 0.508)
    (uvia_drill 0.127)
    (uvias_allowed no)
    (uvia_min_size 0.508)
    (uvia_min_drill 0.127)
    (pcb_text_width 0.3)
    (pcb_text_size 1.5 1.5)
    (mod_edge_width 0.15)
    (mod_text_size 1.5 1.5)
    (mod_text_width 0.15)
    (pad_size 0.0005 0.0005)
    (pad_drill 0)
    (pad_to_mask_clearance 0.2)
    (aux_axis_origin 0 0)
    (visible_elements 7FFFFFFF)
    (pcbplotparams
      (layerselection 3178497)
      (usegerberextensions true)
      (excludeedgelayer true)
      (linewidth 50000)
      (plotframeref false)
      (viasonmask false)
      (mode 1)
      (useauxorigin false)
      (hpglpennumber 1)
      (hpglpenspeed 20)
      (hpglpendiameter 15)
      (hpglpenoverlay 2)
      (psnegative false)
      (psa4output false)
      (plotreference true)
      (plotvalue true)
      (plotothertext true)
      (plotinvisibletext false)
      (padsonsilk false)
      (subtractmaskfromsilk false)
      (outputformat 1)
      (mirror false)
      (drillshape 1)
      (scaleselection 1)
      (outputdirectory ""))
  )

  (net 0 "")
  (net 1 /SIGNAL)
  (net 2 GND)

  (net_class Default "Ceci est la Netclass par défaut"
    (clearance 0.254)
    (trace_width 0.254)
    (via_dia 0.889)
    (via_drill 0.635)
    (uvia_dia 0.508)
    (uvia_drill 0.127)
    (add_net "")
    (add_net /SIGNAL)
  )

  (net_class POWER ""
    (clearance 0.254)
    (trace_width 0.5)
    (via_dia 1.2)
    (via_drill 0.635)
    (uvia_dia 0.508)
    (uvia_drill 0.127)
    (add_net GND)
  )

  (module R3 (layer top_side.Cu) (tedit 4E4C0E65) (tstamp 5127A136)
    (at 66.04 33.3502)
    (descr "Resitance 3 pas")
    (tags R)
    (path /5127A011)
    (autoplace_cost180 10)
    (fp_text reference R1 (at 0 0.127) (layer F.SilkS) hide
      (effects (font (size 1.397 1.27) (thickness 0.2032)))
    )
    (fp_text value 330K (at 0 0.127) (layer F.SilkS)
      (effects (font (size 1.397 1.27) (thickness 0.2032)))
    )
    (fp_line (start -3.81 0) (end -3.302 0) (layer F.SilkS) (width 0.2032))
    (fp_line (start 3.81 0) (end 3.302 0) (layer F.SilkS) (width 0.2032))
    (fp_line (start 3.302 0) (end 3.302 -1.016) (layer F.SilkS) (width 0.2032))
    (fp_line (start 3.302 -1.016) (end -3.302 -1.016) (layer F.SilkS) (width 0.2032))
    (fp_line (start -3.302 -1.016) (end -3.302 1.016) (layer F.SilkS) (width 0.2032))
    (fp_line (start -3.302 1.016) (end 3.302 1.016) (layer F.SilkS) (width 0.2032))
    (fp_line (start 3.302 1.016) (end 3.302 0) (layer F.SilkS) (width 0.2032))
    (fp_line (start -3.302 -0.508) (end -2.794 -1.016) (layer F.SilkS) (width 0.2032))
    (pad 1 thru_hole circle (at -3.81 0) (size 1.397 1.397) (drill 0.812799)
      (layers *.Cu *.Mask F.SilkS)
      (net 1 /SIGNAL)
    )
    (pad 2 thru_hole circle (at 3.81 0) (size 1.397 1.397) (drill 0.812799)
      (layers *.Cu *.Mask F.SilkS)
      (net 2 GND)
    )
    (model discret/resistor.wrl
      (at (xyz 0 0 0))
      (scale (xyz 0.3 0.3 0.3))
      (rotate (xyz 0 0 0))
    )
  )

  (module CP4 (layer top_side.Cu) (tedit 5127A26C) (tstamp 5127A146)
    (at 66.1416 36.8808)
    (descr "Condensateur polarise")
    (tags CP)
    (path /50FD6D39)
    (fp_text reference C1 (at 0.508 0) (layer F.SilkS)
      (effects (font (size 1.27 1.397) (thickness 0.254)))
    )
    (fp_text value 10uF (at 0.8584 2.1192) (layer F.SilkS) hide
      (effects (font (size 1.27 1.143) (thickness 0.254)))
    )
    (fp_line (start 5.08 0) (end 4.064 0) (layer F.SilkS) (width 0.3048))
    (fp_line (start 4.064 0) (end 4.064 1.016) (layer F.SilkS) (width 0.3048))
    (fp_line (start 4.064 1.016) (end -3.556 1.016) (layer F.SilkS) (width 0.3048))
    (fp_line (start -3.556 1.016) (end -3.556 -1.016) (layer F.SilkS) (width 0.3048))
    (fp_line (start -3.556 -1.016) (end 4.064 -1.016) (layer F.SilkS) (width 0.3048))
    (fp_line (start 4.064 -1.016) (end 4.064 0) (layer F.SilkS) (width 0.3048))
    (fp_line (start -5.08 0) (end -4.064 0) (layer F.SilkS) (width 0.3048))
    (fp_line (start -3.556 0.508) (end -4.064 0.508) (layer F.SilkS) (width 0.3048))
    (fp_line (start -4.064 0.508) (end -4.064 -0.508) (layer F.SilkS) (width 0.3048))
    (fp_line (start -4.064 -0.508) (end -3.556 -0.508) (layer F.SilkS) (width 0.3048))
    (pad 1 thru_hole rect (at -5.08 0) (size 1.397 1.397) (drill 0.812799)
      (layers *.Cu *.Mask F.SilkS)
      (net 1 /SIGNAL)
    )
    (pad 2 thru_hole circle (at 5.08 0) (size 1.397 1.397) (drill 0.812799)
      (layers *.Cu *.Mask F.SilkS)
      (net 2 GND)
    )
    (model discret/c_pol.wrl
      (at (xyz 0 0 0))
      (scale (xyz 0.4 0.4 0.4))
      (rotate (xyz 0 0 0))
    )
  )

  (gr_text TEST (at 62 31) (layer top_side.Cu)
    (effects (font (size 1.5 1.5) (thickness 0.3)))
  )
  (gr_line (start 58 42) (end 58 29) (angle 90) (layer Edge.Cuts) (width 0.15))
  (gr_line (start 74 42) (end 58 42) (angle 90) (layer Edge.Cuts) (width 0.15))
  (gr_line (start 74 29) (end 74 42) (angle 90) (layer Edge.Cuts) (width 0.15))
  (gr_line (start 58 29) (end 74 29) (angle 90) (layer Edge.Cuts) (width 0.15))

  (segment (start 61.0616 36.8808) (end 61.0616 34.5186) (width 0.254) (layer bottom_side.Cu) (net 1))
  (segment (start 61.0616 34.5186) (end 62.23 33.3502) (width 0.254) (layer bottom_side.Cu) (net 1) (tstamp 5127A159))
  (segment (start 69.85 33.3502) (end 70.993 33.3502) (width 0.5) (layer bottom_side.Cu) (net 2))
  (segment (start 71.2216 33.5788) (end 71.2216 36.8808) (width 0.5) (layer bottom_side.Cu) (net 2) (tstamp 5127A156))
  (segment (start 70.993 33.3502) (end 71.2216 33.5788) (width 0.5) (layer bottom_side.Cu) (net 2) (tstamp 5127A155))

  (zone (net 2) (net_name GND) (layer bottom_side.Cu) (tstamp 5127A1B2) (hatch edge 0.508)
    (connect_pads (clearance 0.2))
    (min_thickness 0.1778)
    (fill (arc_segments 16) (thermal_gap 0.254) (thermal_bridge_width 0.4064))
    (polygon
      (pts
        (xy 59 30) (xy 73 30) (xy 73 41) (xy 59 41)
      )
    )
  )
)
```

